server:
  port: 6777
  address: 0.0.0.0
lavalink:
  server:
    password: "passedaway"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 4000
    frameBufferDurationMs: 5000
    youtubePlaylistLoadLimit: 100
    playerUpdateInterval: 5
    gc-warnings: true
  plugins:
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.8.1"
      repository: "https://maven.lavalink.dev/releases"

plugins:
  lavasrc:
    providers:
      - "ytsearch:\"%ISRC%\""
      - "ytsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      spotify: true
      deezer: false
      yandexmusic: false
      flowerytts: false
      youtube: false
    spotify:
      clientId: "8a68ceea8e4d487db8d0f53868e3fbe8"
      clientSecret: "baed31b449c44253b46dfa3b50e063e6"
      countryCode: "US"
      playlistLoadLimit: 6

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/
  level:
    root: INFO
    lavalink: INFO